" Saner defaults
set nocompatible

" Filetype recognition and auto config
filetype indent plugin on
syntax on

set history=10000       " the maximum

set ttyfast
set belloff=all

"set spell

set encoding=utf-8
set nrformats=hex

set formatoptions+=j
set nojoinspaces        " Dont insert two spaces after .?! when using J or gq

set showmatch           " Show matching brackets.

" GUI improvements
set shortmess+=I        " Don't show greeting screen when starting vim w/o file
set mouse=a             " Enable mouse for all modes
set laststatus=2        " Always show statusbar
set cmdheight=2         " Command window always 2 (avoids hit enter dialogs)
set ruler
set showcmd
set completeopt=longest,menuone,preview
set wildmenu            " Better command line completion
"set wildmode=list:longest
set wildmode=longest:full

" search down into subfolders, provides tab-completion for file related tasks
set path+=**

set cursorline         " Draw a cursorline (makes redrawing slower)

" open new splits to the right or below of the current one
set splitright
set splitbelow
" Searching
set incsearch
set hlsearch
set ignorecase		" Do case insensitive matching...
set smartcase		" ... but respect case if used

"set number
set textwidth=80
set colorcolumn=+1      " sweet!
"display tabs and trailing spaces
set list
"set listchars=tab:».,trail:.,extends:>,precedes:<
"set listchars=extends:⇒,precedes:⇐,tab:▷·,trail:␣,eol:¬
set listchars=extends:⇒,precedes:⇐,tab:▷·,trail:␣

set autowrite           " Automatically save before commands like :next and :make
set autoread            " Automatically reload file if it has changed outside of vim
set display=lastline
"Does not work so well with ctags :/
"set autochdir           " Automatically switch pwd to dir of current file
"set undofile            " persistent undo!
"set undodir=~/.vim
set hidden              " allow unsaved buffers to go into background

set nowrap              " Don't wrap lines
set linebreak           " If yes, then break at convenient points

set noswapfile
"" Tabs
"set smarttab
set expandtab           " Tabs to Spaces
set softtabstop=4       " Fake Tabs feel like real ones when editing
set shiftwidth=4        " A Tab equals 4 spaces


"" Proper Clipboard integration
set clipboard=unnamedplus

"" folding
set foldenable
set foldmethod=indent
" set true colors
" help xterm-true-color (needed to work inside tmux)
set t_8f=[38;2;%lu;%lu;%lum
set t_8b=[48;2;%lu;%lu;%lum
set termguicolors

set background=dark
colorscheme evening

" quick fixes for termguicolors
" replace undercurl with underline
hi SpellBad cterm=underline term=underline
hi SpellCap cterm=underline term=underline
hi SpellRare cterm=underline term=underline
hi SpellLocal cterm=underline term=underline

set backspace=indent,eol,start
set autoindent          " Smooth indenting on newline
" don't underline cursorline
hi Cursorline cterm=None term=None


let g:netrw_banner=0        " disable banner
let g:netrw_browse_split=4  " open file in previous window
let g:netrw_altv=1
let g:netrw_liststyle=3     " tree view


" Turn off cursorline when in insert mode
autocmd InsertEnter,InsertLeave * set cursorline!

" Turn off colorcolumn in quickfix mode
autocmd Filetype qf setlocal colorcolumn=0




"nnoremap <silent> <F8> :TlistToggle<CR>
"let Tlist_Sort_Type = "name"
"let Tlist_Show_One_File = 1
"let Tlist_Enable_Fold_Column = 0
"let Tlist_Use_Right_Window = 1
"let Tlist_Compact_Format = 1
