" Saner defaults
set nocompatible

" Filetype recognition and auto config
filetype indent plugin on
syntax on

"" GUI improvements
set shortmess+=I        " Don't show greeting screen when starting vim w/o file
set mouse=a             " Enable mouse for all modes

set history=10000       " the maximum

set ttyfast
set belloff=all
set lazyredraw

set display=lastline
set ruler
set laststatus=2
set showcmd

set completeopt=longest,menuone,preview,popup

set wildmenu
set wildmode=longest:full,full  " do full completion on second keystroke

" open new split panes to right and bottom
set splitright
set splitbelow

" search down into subfolders, provides tab-completion for file related tasks
" set path+=**
"remove /usr/include from path
set path=.,,

" disable vim's default for C programs to search for includes
set include=

set autowrite           " Automatically save before commands like :next and :make
set autoread

" Searching
set incsearch
set hlsearch
set ignorecase          " Do case insensitive matching...
set smartcase           " ... but respect case if used

set backspace=indent,eol,start
set autoindent

set nowrap              " Don't wrap lines

""display tabs and trailing spaces
set list
set listchars=extends:⇒,precedes:⇐,tab:▷·,trail:␣
set nrformats-=octal

set formatoptions+=j    " Remove comment leader when joining lines

"" Tabs
"set smarttab
set expandtab           " Tabs to Spaces
set softtabstop=4       " Fake Tabs feel like real ones when editing
set shiftwidth=4        " A Tab equals 4 spaces
set shiftround          " round indent (i.e. < >) to multiple of shiftwidth

set textwidth=78

"" Proper Clipboard integration
set clipboard=unnamedplus

"" folding
" the default 'manual' is not very useful
set foldmethod=indent
" but don't fold by default when opening a buffer
set nofoldenable

"" Spelling
set spell

"" Default encoding
set encoding=utf-8

set cursorline         " Draw a cursorline (makes redrawing slower)

" set true colors
" help xterm-true-color (needed to work inside tmux)
set t_8f=[38;2;%lu;%lu;%lum
set t_8b=[48;2;%lu;%lu;%lum
set termguicolors

set background=dark

"" Misc
set nojoinspaces        " Don't insert two spaces after .?! when joining lines

" quick fixes for termguicolors
" replace undercurl with underline
hi SpellBad term=italic cterm=italic ctermbg=None
hi SpellCap term=italic cterm=italic ctermbg=None
hi SpellRare term=italic cterm=italic ctermbg=None
hi SpellLocal term=italic cterm=italic ctermbg=None

" don't underline cursorline
hi Cursorline term=None cterm=None
hi CursorlineNr term=None cterm=None

" netrw options
let g:netrw_banner=0        " disable banner
let g:netrw_liststyle=3     " tree view
let g:netrw_winsize=0       " split new windows equal

" syntastic options
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_aggregate_errors = 1
